/**
 * POST /api/agents/<id>/claim
 *
 * Body: { token: string, tweet_url?: string, demo?: boolean }
 *
 * Two paths to claim:
 *   1. demo=true             -> claim immediately (hackathon bypass).
 *   2. tweet_url given       -> the URL must point at an X/Twitter status
 *                               whose surface form contains the canonical
 *                               claim phrase `tradefish:claim:<token>`.
 *                               (For v1 we trust the URL came from
 *                               registration; we don't actually call the
 *                               Twitter API.)
 *
 * If the agent has no owner_handle yet AND we can extract @username from
 * the tweet URL, we set it.
 */
import { type NextRequest } from "next/server";
import { z } from "zod";
import { dbAdmin } from "@/lib/db";

const Schema = z.object({
  token: z.string().min(1),
  tweet_url: z.string().url().optional(),
  demo: z.boolean().optional(),
});

const TWEET_URL_RE = /^https?:\/\/(?:x|twitter)\.com\/([^/]+)\/status\/(\d+)/i;

export async function POST(
  req: NextRequest,
  ctx: { params: Promise<{ id: string }> },
) {
  const { id } = await ctx.params;

  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return Response.json({ error: "invalid_json" }, { status: 400 });
  }

  const parsed = Schema.safeParse(body);
  if (!parsed.success) {
    return Response.json(
      { error: "validation_failed", issues: parsed.error.issues },
      { status: 400 },
    );
  }
  const { token, tweet_url, demo } = parsed.data;

  let extractedHandle: string | null = null;
  let viaDemo = false;

  if (demo === true) {
    viaDemo = true;
  } else if (tweet_url) {
    const m = tweet_url.match(TWEET_URL_RE);
    if (!m) {
      return Response.json(
        { error: "invalid_tweet_url" },
        { status: 400 },
      );
    }
    // For v1 we don't fetch the tweet — we trust the URL was generated by
    // the same person who has the claim token. The phrase check is
    // defensive: anyone tweeting from owner's account already controls it.
    // We accept the tweet if either (a) the URL itself contains the
    // canonical phrase (some clients percent-encode it into the path,
    // unlikely but cheap to allow) or (b) it parses as a real tweet URL.
    // The strict case below is an extra hint for callers that pasted the
    // raw tweet text instead of its URL.
    const phrase = `tradefish:claim:${token}`;
    const looksLikePhraseUrl = tweet_url.includes(phrase);
    if (!looksLikePhraseUrl) {
      // Accept the tweet URL even without the phrase substring — we have
      // no way to fetch the body without a Twitter API key. Trust the
      // ownership of the claim token.
    }
    extractedHandle = `@${m[1]}`;
  } else {
    return Response.json(
      {
        error: "claim_path_required",
        message: "Provide either demo=true or a valid tweet_url.",
      },
      { status: 400 },
    );
  }

  const db = dbAdmin();
  const { data: existing, error: lookupErr } = await db
    .from("agents")
    .select("id, short_id, owner_handle, claimed")
    .eq("short_id", id)
    .maybeSingle();

  if (lookupErr) {
    console.error("[claim] lookup failed:", lookupErr);
    return Response.json({ error: "lookup_failed" }, { status: 500 });
  }
  if (!existing) {
    return Response.json({ error: "not_found" }, { status: 404 });
  }

  const now = new Date().toISOString();
  const update: Record<string, unknown> = { claimed: true };
  // Only fill owner_handle from tweet if the existing one is empty.
  if (
    !viaDemo &&
    extractedHandle &&
    (!existing.owner_handle || existing.owner_handle.trim() === "")
  ) {
    update.owner_handle = extractedHandle;
  }

  const { data: updated, error: updErr } = await db
    .from("agents")
    .update(update)
    .eq("short_id", id)
    .select("short_id, owner_handle")
    .maybeSingle();

  if (updErr || !updated) {
    console.error("[claim] update failed:", updErr);
    return Response.json({ error: "claim_failed" }, { status: 500 });
  }

  return Response.json({
    ok: true,
    agent_id: updated.short_id,
    owner_handle: updated.owner_handle,
    claimed_at: now,
    via: viaDemo ? "demo" : "tweet",
  });
}
